import { useEffect, useState } from 'react';
import { api } from '../../services/api';

interface Enterprise { id: string; email: string; fullName: string; companyName: string | null; isActive: boolean; lastLoginAt: string | null; jobCount: number; candidateCount: number }
const generatePassword = () => { const bytes = crypto.getRandomValues(new Uint8Array(12)); const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789'; return `A${Array.from(bytes, (byte) => alphabet[byte % alphabet.length]).join('')}7`; };
export function UsersPage() {
  const [users, setUsers] = useState<Enterprise[]>([]); const [search, setSearch] = useState(''); const [active, setActive] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [showCreate, setShowCreate] = useState(false); const [tempPassword, setTempPassword] = useState(''); const [form, setForm] = useState({ email: '', fullName: '', companyName: '', password: '' });
  const load = async () => { setLoading(true); setError(''); try { const { data } = await api.get('/users', { params: { search, isActive: active || undefined, page, limit: 10 } }); setUsers(data.data); setTotal(data.total); } catch { setError('Không thể tải danh sách tài khoản.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [search, active, page]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); try { await api.post('/users', form); setTempPassword(form.password); setForm({ email: '', fullName: '', companyName: '', password: '' }); setShowCreate(false); await load(); } catch (e) { setError((e as { response?: { data?: { error?: { message?: string } } } }).response?.data?.error?.message || 'Không thể tạo tài khoản.'); } };
  const generate = () => setForm({ ...form, password: generatePassword() });
  const toggle = async (user: Enterprise) => { await api.patch(`/users/${user.id}/status`, { isActive: !user.isActive }); await load(); };
  const edit = async (user: Enterprise) => { const fullName = window.prompt('Họ tên', user.fullName); if (fullName === null) return; const companyName = window.prompt('Tên công ty', user.companyName || ''); if (companyName === null) return; try { await api.put(`/users/${user.id}`, { fullName, companyName }); await load(); } catch { setError('Không thể cập nhật tài khoản.'); } };
  const reset = async (user: Enterprise) => { const password = generatePassword(); await api.post(`/users/${user.id}/reset-password`, { password }); setTempPassword(password); };
  const remove = async (user: Enterprise) => { try { const { data } = await api.get(`/users/${user.id}`); const detail = data.data; if (window.confirm(`Xóa ${user.companyName || user.email}? Thao tác này sẽ xóa ${detail.jobCount} JD và ${detail.candidateCount} CV.`)) { await api.delete(`/users/${user.id}`); await load(); } } catch { setError('Không thể xóa tài khoản.'); } };
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Quản lý tài khoản doanh nghiệp</h1><p className="mt-1 text-sm text-slate-500">Tạo và quản lý quyền truy cập của các doanh nghiệp.</p></div><button onClick={() => setShowCreate(true)} className="rounded-lg bg-blue-700 px-4 py-2.5 font-semibold text-white">Tạo tài khoản</button></div>
    {tempPassword && <div role="status" className="flex items-center justify-between rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm"><span>Mật khẩu tạm (chỉ hiển thị lần này): <strong>{tempPassword}</strong></span><button onClick={() => void navigator.clipboard.writeText(tempPassword)} className="font-semibold text-blue-700">Sao chép</button><button onClick={() => setTempPassword('')} aria-label="Đóng">×</button></div>}
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="flex flex-wrap gap-3"><input value={search} onChange={(e) => { setPage(1); setSearch(e.target.value); }} placeholder="Tìm tên, email hoặc công ty" className="min-w-64 rounded-lg border border-slate-300 px-3 py-2"/><select value={active} onChange={(e) => setActive(e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2"><option value="">Tất cả trạng thái</option><option value="true">Hoạt động</option><option value="false">Đã khóa</option></select></div>
    <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{['Công ty', 'Họ tên', 'Email', 'Trạng thái', 'Đăng nhập cuối', 'JD', 'CV', 'Thao tác'].map((heading) => <th key={heading} className="px-4 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-8 text-center text-slate-500">Đang tải…</td></tr> : users.length === 0 ? <tr><td colSpan={8} className="p-8 text-center text-slate-500">Chưa có tài khoản doanh nghiệp.</td></tr> : users.map((u) => <tr key={u.id} className="border-t border-slate-100"><td className="px-4 py-3">{u.companyName}</td><td className="px-4 py-3">{u.fullName}</td><td className="px-4 py-3">{u.email}</td><td className="px-4 py-3">{u.isActive ? 'Hoạt động' : 'Đã khóa'}</td><td className="px-4 py-3">{u.lastLoginAt ? new Date(u.lastLoginAt).toLocaleString('vi-VN') : '—'}</td><td className="px-4 py-3">{u.jobCount}</td><td className="px-4 py-3">{u.candidateCount}</td><td className="space-x-2 px-4 py-3"><button onClick={() => void edit(u)} className="text-blue-700">Sửa</button><button onClick={() => void toggle(u)} className="text-blue-700">{u.isActive ? 'Khóa' : 'Mở khóa'}</button><button onClick={() => void reset(u)} className="text-blue-700">Đặt lại MK</button><button onClick={() => void remove(u)} className="text-red-700">Xóa</button></td></tr>)}</tbody></table></div>
    <div className="flex items-center justify-between text-sm"><span>{total} tài khoản</span><div className="space-x-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-1 disabled:opacity-40">Trước</button><span>{page}</span><button disabled={page * 10 >= total} onClick={() => setPage(page + 1)} className="rounded border px-3 py-1 disabled:opacity-40">Sau</button></div></div>
    {showCreate && <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/40 p-4"><form onSubmit={create} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><h2 className="text-xl font-bold">Tạo tài khoản doanh nghiệp</h2><button type="button" onClick={() => setShowCreate(false)}>×</button></div>{([['email','Email'],['fullName','Họ tên'],['companyName','Tên công ty'],['password','Mật khẩu tạm']] as const).map(([key,label]) => <label key={key} className="block text-sm font-medium">{label}<input required value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} type={key === 'password' ? 'text' : key === 'email' ? 'email' : 'text'} className="mt-1 w-full rounded-lg border px-3 py-2" /></label>)}<button type="button" onClick={generate} className="text-sm font-semibold text-blue-700">Sinh mật khẩu ngẫu nhiên</button><div className="flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded-lg border px-4 py-2">Hủy</button><button className="rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white">Tạo tài khoản</button></div></form></div>}
  </div>;
}
